### ISSUE TITLE
Does GraphQ IR fit for chinese natural languages ?

### ISSUE THREAD

**Issue by feng-1985** [Flitternie/GraphQ_IR#7]
OR any suggestion for chinese kbqa's intermediate representation ? Thanks!

**Comment by Flitternie** [comment]
Theoretically yes but practically unsure. 

GraphQ IR can serve as the middleware between natural language and graph query language to mitigate the semantic gap. But as we have described in our paper, GraphQ IR's natural-language-like syntax is **designated to be aligned to English** rather than Chinese or other languages. We haven't tested it on other natural languages. But I personally think it is still worth a try since translating Chinese to GraphQ IR (like a machine translation task) should be still easier than translating directly to formal languages.

Please note that in our implementation, we used BART-base as the neural semantic parser. To achieve good performance on Chinese natural language input, I would recommend you use other language models that were pretrained on Chinese or multilingual corpus.

**Comment by feng-1985** [comment]
Thanks for you suggestion!
